import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generateStatementPDF = async (
  customer,
  transactions
) => {

  const fileName =
    `statement-${customer._id}.pdf`;

  const uploadsDir =
    path.join(
      process.cwd(),
      "uploads"
    );

  // Create uploads folder if it doesn't exist

  if (
    !fs.existsSync(
      uploadsDir
    )
  ) {

    fs.mkdirSync(
      uploadsDir,
      {
        recursive: true
      }
    );

  }

  const filePath =
    path.join(
      uploadsDir,
      fileName
    );

  const doc =
    new PDFDocument({
      margin: 50
    });

  const stream =
    fs.createWriteStream(
      filePath
    );

  doc.pipe(stream);

  /*
  ==========================
  HEADER
  ==========================
  */

  doc
    .fontSize(26)
    .text(
      "KHATA FLOW",
      {
        align: "center"
      }
    );

  doc
    .fontSize(12)
    .text(
      "Customer Statement",
      {
        align: "center"
      }
    );

  doc.moveDown(2);

  /*
  ==========================
  CUSTOMER DETAILS
  ==========================
  */

  doc
    .fontSize(18)
    .text(
      "Customer Details"
    );

  doc.moveDown(0.5);

  doc.text(
    `Name: ${customer.name}`
  );

  doc.text(
    `Email: ${customer.email}`
  );

  doc.text(
    `Phone: ${customer.phone}`
  );

  doc.text(
    `Current Balance: ₹${customer.currentBalance}`
  );

  doc.text(
    `Generated On: ${new Date().toLocaleDateString()}`
  );

  doc.moveDown(2);

  /*
  ==========================
  TRANSACTION TABLE
  ==========================
  */

  doc
    .fontSize(18)
    .text(
      "Transaction History"
    );

  doc.moveDown();

  const tableTop =
    doc.y;

  doc.text(
    "Date",
    50,
    tableTop
  );

  doc.text(
    "Type",
    180,
    tableTop
  );

  doc.text(
    "Amount",
    300,
    tableTop
  );

  doc.text(
    "Note",
    420,
    tableTop
  );

  doc.moveTo(
    50,
    tableTop + 20
  )
    .lineTo(
      550,
      tableTop + 20
    )
    .stroke();

  let y =
    tableTop + 30;

  transactions.forEach(
    (transaction) => {

      doc.text(

        new Date(
          transaction.createdAt
        ).toLocaleDateString(),

        50,
        y

      );

      doc.text(

        transaction.type,

        180,
        y

      );

      doc.text(

        `₹${transaction.amount}`,

        300,
        y

      );

      doc.text(

        transaction.note ||
          "-",

        420,
        y,

        {
          width: 120
        }

      );

      y += 25;

      if (
        y > 700
      ) {

        doc.addPage();

        y = 50;

      }

    }
  );

  /*
  ==========================
  SUMMARY
  ==========================
  */

  const totalCredit =
    transactions

      .filter(
        (t) =>
          t.type ===
          "CREDIT"
      )

      .reduce(
        (
          sum,
          t
        ) =>
          sum +
          t.amount,
        0
      );

  const totalPayment =
    transactions

      .filter(
        (t) =>
          t.type ===
          "DEBIT"
      )

      .reduce(
        (
          sum,
          t
        ) =>
          sum +
          t.amount,
        0
      );

  doc.moveDown(3);

  doc
    .fontSize(16)
    .text(
      "Summary"
    );

  doc.moveDown();

  doc.text(
    `Total Credit: ₹${totalCredit}`
  );

  doc.text(
    `Total Payments: ₹${totalPayment}`
  );

  doc.text(
    `Outstanding Balance: ₹${customer.currentBalance}`
  );

  /*
  ==========================
  FOOTER
  ==========================
  */

  doc.moveDown(3);

  doc
    .fontSize(10)
    .text(

      "Generated by Khata Flow",

      {
        align:
          "center"
      }

    );

  doc.end();

  return new Promise(

    (
      resolve,
      reject
    ) => {

      stream.on(
        "finish",
        () => {

          console.log(
            "PDF Generated:",
            filePath
          );

          resolve(
            filePath
          );

        }
      );

      stream.on(
        "error",
        (err) => {

          console.error(
            "PDF Stream Error:",
            err
          );

          reject(
            err
          );

        }
      );

    }

  );

};